development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: bricolage
  username: bricolage
  password: bricolage
  encoding: unicode
  pool: 1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: bricolage_test
  username: bricolage
  password: bricolage
  encoding: unicode
  pool: 1
